// OneShot E2E driver — submission + live observation + persistence.
import {
  existsSync,
  mkdirSync,
  readFileSync,
  writeFileSync,
} from "node:fs";
import { join } from "node:path";
import {
  EVIDENCE,
  ROOT,
  TOKEN,
  dumpEvidence,
  evidence,
  sleep,
  waitFor,
} from "./cdp-core.mjs";
import { cdp, evaluate, screenshot, startSession } from "./cdp-session.mjs";

const BASE_URL = process.env.ONESHOT_BASE_URL || "http://127.0.0.1:8787";
const ARTIFACTS = join(EVIDENCE, "artifacts");
mkdirSync(ARTIFACTS, { recursive: true });

const PROMPT_TEXT = [
  "Create a production-quality LLM Judge evaluation skill for software projects.",
  "",
  "The evaluator must define:",
  "",
  "- evaluator role and objective;",
  "- accepted evidence;",
  "- evidence hierarchy;",
  "- architecture evaluation;",
  "- implementation evaluation;",
  "- testing evaluation;",
  "- security evaluation;",
  "- documentation evaluation;",
  "- deployment-readiness evaluation;",
  "- issue severities;",
  "- scoring rules;",
  "- missing-evidence handling;",
  "- final recommendation rules;",
  "- a strict structured JSON output contract;",
  "- explicit distinction between observed evidence and inference;",
  "- prohibition against fabricating verification results.",
  "",
  "The substantive result must be generated by the configured production Researcher provider and must execute through the complete canonical OneShot workflow.",
].join("\n");

const REQUIRED_PROCESSORS = [
  "Researcher", "Planner", "Refactor", "GapAnalysis", "Evaluation",
  "SchemaValidation", "FixtureValidation", "GoalValidation", "TripleValidation",
  "Confirmed", "CreateHash", "Builder", "Hash", "Done",
];

const seen = new Map();
export const stageFirstSeen = {};

function recordEvent(e) {
  if (!e || !e.event_id || seen.has(e.event_id)) return false;
  seen.set(e.event_id, e);
  evidence.sse.push(e);
  console.log(
    `[evt] #${e.sequence} ${e.processor} ${e.state}` +
      (e.result ? ` result=${e.result}` : "") +
      (e.artifact_id ? ` artifact=${String(e.artifact_id).slice(0, 50)}` : "") +
      (e.message ? ` | ${String(e.message).slice(0, 100)}` : ""),
  );
  if (e.processor && !stageFirstSeen[e.processor]) {
    stageFirstSeen[e.processor] = {
      at: new Date().toISOString(),
      sequence: e.sequence,
      state: e.state,
    };
  }
  return true;
}

export async function pullNewEvents() {
  const raw = await evaluate(
    `(window.__oneshotEvents||[]).map(function(e){return JSON.stringify(e)}).join('\\n')`,
  );
  if (typeof raw !== "string" || !raw) return;
  for (const line of raw.split("\n")) {
    if (!line.trim()) continue;
    try {
      recordEvent(JSON.parse(line));
    } catch {}
  }
}

export function hasStage(name) {
  return Boolean(stageFirstSeen[name]);
}

export async function grabWindowRecords() {
  const raw = await evaluate(
    `JSON.stringify({requests:(window.__oneshotRequests||[]).map(function(r){return {url:r.url,method:r.method,status:r.status,body:(r.body||'').slice(0,4000)}}), sse:(window.__oneshotSSE||[])})`,
  );
  if (typeof raw !== "string") return;
  try {
    const parsed = JSON.parse(raw);
    evidence.requests = parsed.requests;
    evidence.sse_streams = parsed.sse;
  } catch {}
}

export function extractIds() {
  const convPost = evidence.requests.find(
    (r) => r.method === "POST" && r.url.endsWith("/api/conversations") && r.body,
  );
  if (convPost) {
    try {
      evidence.conversation_created = JSON.parse(convPost.body).conversation_id
        ? JSON.parse(convPost.body)
        : evidence.conversation_created;
    } catch {}
  }
  const convResp = evidence.requests.find(
    (r) => r.method === "POST" && r.url.endsWith("/api/conversations") && r.status === 201,
  );
  const runPost = evidence.requests.find(
    (r) => r.method === "POST" && /\/api\/conversations\/[^/]+\/run$/.test(r.url),
  );
  evidence.run_post = runPost || null;
  // response bodies are captured by the page tap (window records)
  const msgDone = seen.size ? [...seen.values()] : [];
  const runEvents = msgDone.filter((e) => e.run_id);
  evidence.run_id_extracted_from_events = runEvents.length ? runEvents[0].run_id : null;
}

export async function apiGet(path) {
  const res = await fetch(`${BASE_URL}${path}`, {
    headers: { authorization: `Bearer ${TOKEN}` },
  });
  return { status: res.status, body: res.ok ? await res.json() : null };
}

// ── observation loop ──────────────────────────────────────────────────────────
const shotTaken = {};

export async function observeUntilDone(timeoutMs = 420_000) {
  const deadline = Date.now() + timeoutMs;
  let lastSeq = 0;
  while (Date.now() < deadline) {
    await pullNewEvents();
    await resolveIdsFromPage();

    const events = evidence.sse;
    const latest = events[events.length - 1];
    const done = events.find(
      (e) => e.processor === "Done" && e.state === "COMPLETE",
    );

    // §26 live intermediate screenshots (best effort, once each)
    if (!shotTaken["03"] && hasStage("Researcher")) {
      shotTaken["03"] = true;
      await sleep(500);
      await screenshot("03-researcher-running.png");
    }
    if (
      !shotTaken["04"] &&
      (hasStage("GoalValidation") || hasStage("TripleValidation"))
    ) {
      shotTaken["04"] = true;
      await sleep(300);
      await screenshot("04-validation-running.png");
    }
    if (!shotTaken["05"] && hasStage("Builder")) {
      shotTaken["05"] = true;
      await screenshot("05-builder-running.png");
      // Builder may complete in <1s: take a second shot to catch visible state
      await sleep(700);
      await screenshot("06-builder-trace.png");
    }

    if (latest && latest.sequence > lastSeq) lastSeq = latest.sequence;
    if (done) {
      evidence.done_event = done;
      if (!shotTaken["06_done"]) {
        await sleep(2000); // let the UI render the completion message
        await screenshot("06-done.png");
        shotTaken["06_done"] = true;
      }
      return done;
    }
    if (
      events.some(
        (e) => e.state === "COMPLETE" && e.result === "ROOT_CAUSE" && e.processor === "Done",
      )
    ) {
      return null; // handled by caller via evidence
    }
    await sleep(200);
  }
  throw new Error("observation timeout before Done");
}

export async function finalUIProof() {
  // expand the in-chat per-stage workflow trace ("Show activities")
  const expanded = await evaluate(
    `(function(){
      const btns = [...document.querySelectorAll('button')].filter(b => b.textContent.includes('Show activities'));
      btns.forEach(b => b.click());
      return btns.length;
    })()`,
  );
  evidence.dom.activity_toggle_count = expanded;
  await sleep(900);
  evidence.dom.final_chat_text = await evaluate(
    `[...document.querySelectorAll('p')].map(p => p.textContent).join('\\n=====\\n').slice(0, 6000)`,
  );
  evidence.dom.page_text_head = await evaluate(
    `document.body.textContent.slice(0, 400)`,
  );
  await screenshot("05b-final-chat-output.png");

  // open the task drawer for the trace proof
  await evaluate(`document.querySelector('button[aria-label="Task review"]').click()`);
  await sleep(700);
  evidence.dom.task_drawer_final_text = await evaluate(
    `(document.querySelector('[role="menu"]')?.textContent || '').slice(0, 400)`,
  );
  await screenshot("05c-task-drawer-final.png");
  await evaluate(`document.querySelector('button[aria-label="Task review"]').click()`);
  await sleep(300);
}

export async function persistenceProof() {
  // 1. refresh the browser
  await cdp.send("Page.reload");
  await waitFor("page reload", async () =>
    (await evaluate("document.readyState")) === "complete" ? true : undefined,
  );
  await waitFor("chat input after reload", async () =>
    (await evaluate(
      `!!document.querySelector('textarea[placeholder="Message OneShot..."]')`,
    )) ? true : undefined,
  );
  await sleep(1200);
  evidence.persistence.ui_chat_after_reload = await evaluate(
    `document.body.textContent.includes('OneShot Canonical Execution Completed')`,
  );
  await screenshot("07-after-refresh.png");

  // 2. backend persistence checks
  if (evidence.run_id) {
    const snap = await apiGet(`/api/runs/${evidence.run_id}`);
    evidence.persistence.run_snapshot_status = snap.status;
    evidence.persistence.run_result = snap.body?.result;
    evidence.persistence.run_event_count = snap.body?.events?.length;
    evidence.persistence.hash_proof = snap.body?.hash_proof ?? null;
    const task = await apiGet(`/api/runs/${evidence.run_id}/task`);
    evidence.persistence.task_projection_status = task.status;
  }
  if (evidence.conversation_id) {
    const conv = await apiGet(`/api/conversations/${evidence.conversation_id}`);
    evidence.persistence.conversation_status = conv.status;
    evidence.persistence.conversation_turns = conv.body?.turns?.length;
    evidence.persistence.conversation_revision = conv.body?.intent?.revision;
  }
}

export async function main() {
  try {
    await startSession();
    await observeLaunchProof();
    await submitPrompt();
    await observeUntilDone();
    await finalUIProof();
    await collectArtifacts();
    await grabBackendProof();
    await persistenceProof();
    evidence.status = "driver-completed";
  } catch (e) {
    evidence.status = "driver-error";
    evidence.driver_error = String(e && e.stack ? e.stack : e);
    console.error("[driver-error]", e);
  } finally {
    dumpEvidence();
  }
}

async function submitPrompt() {
  const setPrompt = `
    (function(){
      const ta = document.querySelector('textarea[placeholder="Message OneShot..."]');
      if (!ta) return 'NO_TEXTAREA';
      const setter = Object.getOwnPropertyDescriptor(window.HTMLTextAreaElement.prototype, 'value').set;
      setter.call(ta, ${JSON.stringify(PROMPT_TEXT)});
      ta.dispatchEvent(new Event('input', { bubbles: true }));
      return 'OK';
    })()
  `;
  const setResult = await evaluate(setPrompt);
  if (setResult !== "OK") throw new Error("prompt fill failed: " + JSON.stringify(setResult));
  await sleep(500);
  evidence.prompt_in_composer = (
    await evaluate(
      `document.querySelector('textarea[placeholder="Message OneShot..."]').value.slice(0, 200)`,
    )
  ).slice(0, 200);
  console.log("[submit] clicking Send message");
  evidence.submitted_at = new Date().toISOString();
  await evaluate(`document.querySelector('button[title="Send message"]').click()`);
  await waitFor("user message visible", async () => {
    const has = await evaluate(
      `document.body.textContent.includes('Create a production-quality LLM Judge')`,
    );
    return has ? true : undefined;
  });
  await sleep(1200);
  await resolveIdsFromPage();
  await screenshot("02-prompt-submitted.png");
}

async function resolveIdsFromPage() {
  const raw = await evaluate(
    `JSON.stringify((window.__oneshotRequests||[]).filter(function(r){return r.url.indexOf('/api/conversations')>=0;}))`,
  );
  if (typeof raw !== "string") return;
  let recs = [];
  try {
    recs = JSON.parse(raw);
  } catch {
    return;
  }
  for (const r of recs) {
    if (r.method === "POST" && r.url.endsWith("/api/conversations") && r.body) {
      const arrow = r.body.indexOf("=>");
      const respText = arrow >= 0 ? r.body.slice(arrow + 2) : "";
      try {
        const resp = JSON.parse(respText);
        if (resp.conversation_id) {
          evidence.conversation_id = resp.conversation_id;
          evidence.intent_revision = resp.intent?.revision;
          evidence.intent_ready_for_prompt = resp.intent?.ready_for_prompt;
        }
      } catch {}
      evidence.conversation_request_body = r.body.slice(0, 300);
      evidence.conversation_api_status = r.status;
    }
    if (r.method === "POST" && /\/api\/conversations\/[^/]+\/run$/.test(r.url)) {
      const arrow = r.body.indexOf("=>");
      const respText = arrow >= 0 ? r.body.slice(arrow + 2) : "";
      try {
        const resp = JSON.parse(respText);
        if (resp.run_id) evidence.run_id = resp.run_id;
        if (resp.prompt_id) evidence.prompt_id = resp.prompt_id;
        if (resp.intent_id) evidence.intent_id = resp.intent_id;
        evidence.run_api_status = r.status;
      } catch {}
    }
  }
}

export async function collectArtifacts() {
  if (!evidence.run_id) return;
  const names = [
    "prompt", "researcher", "plan.researcher", "audit", "plan.refactored",
    "plan.gap", "gap", "evaluation", "triple-validation", "confirmed",
    "confirmed-hash", "builder-result", "hash-proof",
  ];
  for (const name of names) {
    try {
      const res = await fetch(
        `${BASE_URL}/api/runs/${evidence.run_id}/artifacts/${name}`,
        { headers: { authorization: `Bearer ${TOKEN}` } },
      );
      if (!res.ok) continue;
      const data = await res.json();
      evidence.artifacts[name] = data;
      writeFileSync(
        join(ARTIFACTS, `${name}.json`),
        JSON.stringify(data, null, 2),
      );
      console.log(`[artifact] ${name} saved (${JSON.stringify(data).length}B)`);
    } catch (e) {
      console.log(`[artifact] ${name} FAILED: ${e.message}`);
    }
  }
}

async function observeLaunchProof() {
  evidence.ui = {};
  evidence.ui.chat_input_visible = await evaluate(
    `!!document.querySelector('textarea[placeholder="Message OneShot..."]')`,
  );
  evidence.ui.send_button_visible = await evaluate(
    `!!document.querySelector('button[title="Send message"]')`,
  );
  evidence.ui.task_drawer_trigger = await evaluate(
    `!!document.querySelector('button[aria-label="Task review"]')`,
  );
  evidence.ui.header_text = await evaluate(
    `(document.querySelector('header')?.textContent || '').slice(0, 160)`,
  );
  evidence.ui.page_title = await evaluate("document.title");
  await screenshot("01-ui-start.png");

  await evaluate(
    `document.querySelector('button[aria-label="Task review"]').click()`,
  );
  await sleep(600);
  evidence.ui.task_drawer_open_text = await evaluate(
    `(document.querySelector('[role="menu"]')?.textContent || '').slice(0, 260)`,
  );
  await screenshot("01b-task-drawer-open.png");
  await evaluate(
    `document.querySelector('button[aria-label="Task review"]').click()`,
  );
  await sleep(300);
}

async function grabBackendProof() {
  if (!evidence.run_id) return;
  const snap = await apiGet(`/api/runs/${evidence.run_id}`);
  evidence.run_snapshot = snap.body;
  const sandbox = await apiGet(`/api/runs/${evidence.run_id}/sandbox`);
  evidence.sandbox_evidence = sandbox.body;
  const task = await apiGet(`/api/runs/${evidence.run_id}/task`);
  evidence.task_projection_status = task.status;
  try {
    const evFile = join(
      ROOT,
      "data",
      "task-events",
      `${evidence.run_id}.jsonl`,
    );
    if (existsSync(evFile)) {
      evidence.task_events_file = evFile;
      evidence.task_events_lines = readFileSync(evFile, "utf8").trim().split("\n").length;
    }
  } catch {}
}

main();
