import { createVisualSettings } from '/visual-settings.js';
import { createStateMachine } from '/runtime-view-state.js';
import { createLiveActivity } from '/live-activity.js';
import { createTaskManagement } from '/task-management.js';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const STAGES=['Planner','Refactor','Gap Analysis','Evaluation','Triple Validation','Schema Validation','Fixture Validation','Goal Validation','Confirmed','Builder','Hash Verification','Done'];
const state={conversationId:localStorage.getItem('oneshot.currentConversationId')||'',promptId:localStorage.getItem('oneshot.currentPromptId')||'',runId:localStorage.getItem('oneshot.currentRunId')||'',ready:false,run:null,seen:new Set(),source:null,eventAbort:null,authToken:sessionStorage.getItem('oneshot.accessToken')||'',drawer:null,side:false,top:true,activeView:'chat'};

const ROLES=[['Planner',['Planner']],['Refactor',['Refactor']],['Gap Analysis',['Gap Analysis']],['Evaluation',['Evaluation']],['Triple Validation',['Triple Validation','Schema Validation','Fixture Validation','Goal Validation']],['Builder',['Builder','Hash Verification']],['Result',['Confirmed','Done']]];
const slug=s=>s.toLowerCase().replace(/[^a-z0-9]+/g,'-');
$('#stages').innerHTML=ROLES.map(([role,stages])=>`<details class="role-group" data-role="${role}" data-testid="role-${slug(role)}"><summary><span class="role-name">${role}</span><em>PENDING</em></summary>${stages.map((s,i)=>`<div class="stage${i>0?' stage-child':''}" data-stage="${s}"><span>${s}</span><em>PENDING</em></div>`).join('')}<div class="role-tasks" data-role-tasks="${role}" aria-label="${role} tasks"></div></details>`).join('');
function toast(t){$('#toast').textContent=t;$('#toast').classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('#toast').classList.remove('show'),2200)}
function setConnection(kind,detail=''){const label={connected:'Connected',connecting:'Connecting',reconnecting:'Reconnecting',disconnected:'Runtime unavailable',auth:'Authentication required'}[kind]||kind;$('#runtime-label').textContent=detail?`${label} · ${detail}`:label;$('#rail-status').className=`rail-status ${kind}`}
function headers(extra={}){const h={...extra};if(state.authToken)h.Authorization=`Bearer ${state.authToken}`;return h}
async function apiFetch(url,options={}){const r=await fetch(url,{credentials:'same-origin',...options,headers:headers(options.headers||{})});if(r.status===401){setConnection('auth');showAuth();throw new Error('Authentication required')}if(r.status===403&&!state.authToken){setConnection('auth','session mutation rejected');showAuth('Cookie-authenticated mutation was rejected. Enter the local OneShot access token or use the existing session login flow.');throw new Error('Authentication/CSRF required')}return r}
function showAuth(msg=''){$('#auth-error').textContent=msg;$('#auth-overlay').classList.add('open');setTimeout(()=>$('#auth-token').focus(),0)}function hideAuth(){$('#auth-overlay').classList.remove('open');$('#auth-error').textContent=''}
$('#auth-cancel').onclick=hideAuth;$('#auth-form').onsubmit=async e=>{e.preventDefault();const token=$('#auth-token').value.trim();if(!token){$('#auth-error').textContent='Enter the local OneShot access token.';return}state.authToken=token;sessionStorage.setItem('oneshot.accessToken',token);$('#auth-token').value='';hideAuth();await bootstrap()};
// --- Locked state-adaptive modules (semantic state, live lane, TODO hierarchy, visual settings) ---
const live=createLiveActivity();live.bindDivider();
const view=createStateMachine($('#app'),{onChange:s=>{live.setLiveVisible(s!=='IDLE');if(s!=='IDLE'&&$('#app').classList.contains('sidebar-off')){$('#app').classList.remove('sidebar-off');syncSide();syncLayout()}}});
const tasks=createTaskManagement({apiFetch});tasks.bindManualToggles();
const visual=createVisualSettings($('#app'));visual.renderInto($('#settings-popover'));visual.bindToggle($('#settings-button'),$('#settings-popover'));

function setReadiness(level,ready,label){state.ready=!!ready;$('#ready-label').textContent=label||'Information';$$('#readiness i').forEach((e,i)=>e.className=i<level?'ready':(!ready&&i===level?'wait':''));$('#generate').disabled=!state.ready||!state.conversationId;$('#readiness').setAttribute('aria-label',`${level} of 3 readiness signals. ${ready?'Ready to generate':'Awaiting runtime evaluation'}`)}
function addMessage(role,text,id=''){if(!text)return;if(id&&$(`[data-message-id="${CSS.escape(id)}"]`))return;$('#welcome')?.remove();const a=document.createElement('article');a.className=`message ${role}`;a.dataset.testid=`chat-message-${role}`;if(id)a.dataset.messageId=id;a.innerHTML=`<b>${role==='user'?'ML':'1S'}</b><div><small>${role==='user'?'You':role==='assistant'?'OneShot':'System'}</small><p></p></div>`;a.querySelector('p').textContent=text;$('#chat').append(a);$('#chat').scrollTop=$('#chat').scrollHeight}
function normalizeConversation(c){const turns=Array.isArray(c?.turns)?c.turns:[];$('#chat').innerHTML='';for(const t of turns){const role=t.role==='assistant'?'assistant':'user';const text=t.message??t.text??t.user_message??'';if(text)addMessage(role,text,t.turn_id||t.id||'')}const intent=c?.intent||c?.current_intent||{};return{intent,help:c?.help_request||intent?.help_request}}

function openDrawer(name){state.drawer=name;const t=name==='tasks',c=name==='context';$('#tasks').classList.toggle('open',t);$('#context').classList.toggle('open',c);$('#tasks-button').classList.toggle('active',t);$('#context-button').classList.toggle('active',c);$('#app').classList.toggle('drawer-open',!!name);syncLayout()}
function closeDrawers(){openDrawer(null)}
$('#tasks-button').onclick=()=>state.drawer==='tasks'?closeDrawers():openDrawer('tasks');$('#context-button').onclick=()=>state.drawer==='context'?closeDrawers():openDrawer('context');$$('[data-close]').forEach(b=>b.onclick=closeDrawers);
function syncSide(){state.side=!$('#app').classList.contains('sidebar-off');$('#sidebar-toggle').setAttribute('aria-expanded',String(state.side));$('#side-handle').setAttribute('aria-expanded',String(state.side));$('#side-handle').textContent=state.side?'‹':'›'}
function toggleSide(){if(!state.side&&state.drawer)closeDrawers();state.side=!state.side;$('#app').classList.toggle('sidebar-off',!state.side);syncSide();syncLayout()}$('#sidebar-toggle').onclick=toggleSide;$('#side-handle').onclick=toggleSide;
$('#top-handle').onclick=()=>{state.top=!state.top;$('#app').classList.toggle('top-off',!state.top);$('#top-handle').textContent=state.top?'⌃':'⌄';$('#top-handle').setAttribute('aria-expanded',String(state.top));syncLayout()};
$$('[data-view]').forEach(b=>b.onclick=()=>{state.activeView=b.dataset.view;$$('[data-view]').forEach(x=>x.classList.toggle('active',x===b));$('#chat').hidden=state.activeView!=='chat';$('#work-view').hidden=state.activeView!=='work'});

function renderTreeNodes(nodes,root=$('#workspace-tree'),depth=0){if(depth===0)root.textContent='';for(const n of nodes||[]){const name=n?.name||String(n?.path||'workspace').split(/[\\/]/).filter(Boolean).at(-1)||'workspace';const path=n?.path||name;const kids=Array.isArray(n?.children)?n.children:Array.isArray(n?.entries)?n.entries:[];const folder=n?.type==='folder'||n?.kind==='folder'||n?.directory===true||kids.length>0;const b=document.createElement('button');b.className='tree-row';b.style.paddingLeft=`${8+depth*14}px`;b.textContent=`${folder?'▾':'·'} ${name}`;if(!folder)b.onclick=()=>openWorkspaceFile(path);root.append(b);if(kids.length)renderTreeNodes(kids,root,depth+1)}}
async function loadWorkspace(){const s=$('#workspace-state');s.textContent='Loading workspace…';s.className='workspace-state';try{const r=await apiFetch('/v1/workspace/tree?path=.&depth=3');if(!r.ok)throw new Error(`Workspace tree failed: ${r.status}`);const d=await r.json();const nodes=d&&Array.isArray(d.nodes)?d.nodes:(Array.isArray(d)&&d);let list=Array.isArray(nodes)?nodes:[];if(!list.length&&d){const alt=d.tree??d.entries??null;if(Array.isArray(alt))list=alt;else if(alt&&Array.isArray(alt.children))list=alt.children;else if(d.root&&typeof d.root==='object')list=d.root.children||[];}renderTreeNodes(list.filter(Boolean));s.textContent=''}catch(e){if(String(e).includes('Authentication'))return;s.textContent=`Workspace unavailable: ${e.message||e}`;s.className='workspace-state error'}}
async function openWorkspaceFile(path){try{const r=await apiFetch(`/v1/workspace/file?path=${encodeURIComponent(path)}`);if(!r.ok)throw new Error(`File read failed: ${r.status}`);const raw=await r.text();let content=raw;try{const d=JSON.parse(raw);content=d.content??d.text??d.file?.content??raw}catch{}addMessage('assistant',`Opened ${path}`);const pre=document.createElement('pre');pre.className='file-view';pre.textContent=content;$('#chat').append(pre)}catch(e){toast(e.message||String(e))}}

function normalizeEvent(raw){return{eventId:String(raw.event_id??raw.eventId??`${raw.run_id||state.runId||'run'}:${raw.sequence}:${raw.processor}`),sequence:Number(raw.sequence??0),runId:String(raw.run_id??state.runId??''),processor:String(raw.processor||'Unknown'),scope:raw.scope||'WORKFLOW',state:raw.state||'PENDING',result:raw.result,activity:raw.activity,message:raw.message,artifactId:raw.artifact_id??raw.artifactId,promptId:raw.prompt_id??raw.promptId,timestamp:raw.created_at??raw.timestamp}}
function setStage(e){const target=e.processor==='Researcher'?$('#researcher summary'):$(`[data-stage="${CSS.escape(e.processor)}"]`);if(target){const em=target.querySelector('em');if(em)em.textContent=e.state;target.dataset.state=e.state}if(e.processor==='Researcher'&&e.activity){const a=document.createElement('div');a.className='activity';a.textContent=e.activity;$('#researcher-activity').append(a)}if(e.promptId){state.promptId=String(e.promptId);localStorage.setItem('oneshot.currentPromptId',state.promptId)}$('#run-meta').textContent=[state.promptId&&`Prompt(${state.promptId})`,state.runId&&`Run ${state.runId}`].filter(Boolean).join(' · ')||'Waiting for a real run'}
function isTerminalEvent(e){return e.processor==='Done'&&(e.state==='COMPLETE'||e.state==='COMPLETED')}
async function applyEvent(raw){const e=normalizeEvent(raw);if(state.seen.has(e.eventId))return;state.seen.add(e.eventId);state.run.events.push(e);state.run.events.sort((a,b)=>a.sequence-b.sequence);setStage(e);view.onEvent(e);live.onEvent(e);tasks.onEvent(e);renderWork();if(isTerminalEvent(e)){await refreshRun();if(e.message)addMessage(e.result==='PASSED'?'assistant':'system',e.message,`done:${e.eventId}`);closeEvents()}}
function contextFromSnapshot(s){return s?.run_context??s?.context??s?.input??s?.agent_input??s?.build_requirement??null}
function renderRunResult(s,result){const isPassed=result==='PASSED'||result==='COMPLETED';const createdHash=s?.hash_proof?.created_hash||s?.created_hash||s?.hash||'—';const recomputedHash=s?.hash_proof?.recomputed_hash||s?.recomputed_hash||s?.hash||'—';const proofValid=s?.hash_proof?.equal??(createdHash&&recomputedHash&&createdHash===recomputedHash&&createdHash!=='—');return `<div class="result-card ${isPassed?'result-passed':'result-failed'}"><div class="result-header"><span class="result-badge ${isPassed?'badge-passed':'badge-failed'}"><i class="result-icon">${isPassed?'✓':'⚠'}</i> ${escapeText(result)}</span><span class="result-proof-tag">${proofValid?'RFC 8785 Proof: VALID':'RFC 8785 Proof: PENDING'}</span></div><div class="result-hashes"><div class="result-hash-item"><span class="hash-tag">Created Hash</span><code class="hash-val" title="${escapeText(String(createdHash))}">${escapeText(String(createdHash).slice(0,18))}…</code></div><div class="result-hash-item"><span class="hash-tag">Recomputed</span><code class="hash-val" title="${escapeText(String(recomputedHash))}">${escapeText(String(recomputedHash).slice(0,18))}…</code></div></div><div class="result-footer"><span class="result-eq">Proof Equality: <strong class="${proofValid?'eq-match':'eq-mismatch'}">${proofValid?'MATCH':'MISMATCH'}</strong></span><details class="result-raw-json"><summary>Inspect Raw Snapshot JSON</summary><pre>${escapeText(JSON.stringify(s,null,2))}</pre></details></div></div>`}
function showSnapshot(s){state.run.snapshot=s;const ctx=contextFromSnapshot(s);$('#context-value').textContent=ctx?JSON.stringify(ctx,null,2):'Run context is not exposed by the current runtime snapshot.';const result=s?.result??state.run.events.filter(isTerminalEvent).at(-1)?.result;if(result){$('#run-result').innerHTML=renderRunResult(s,result);$('#run-result').dataset.result=result;$('#run-result').dataset.snapshot=JSON.stringify(s);}live.onSnapshot(s);void tasks.onSnapshot(s,state.runId);renderWork()}
async function refreshRun(){if(!state.runId)return;const r=await apiFetch(`/api/runs/${encodeURIComponent(state.runId)}`);if(!r.ok)throw new Error(`Run snapshot failed: ${r.status}`);const s=await r.json();showSnapshot(s);if(Array.isArray(s.events)){for(const raw of [...s.events].sort((a,b)=>(a.sequence??0)-(b.sequence??0)))await applyEvent(raw)}}
function renderWork(){if(!state.run){$('#work-empty').hidden=false;$('#work-content').innerHTML='';return}$('#work-empty').hidden=true;const last=state.run.events.at(-1);const s=state.run.snapshot||{};const result=s.result||last?.result||last?.state||'PENDING';const proof=s.hash_proof;$('#work-content').innerHTML=`<section class="work-card"><strong>Run</strong><pre>${escapeText(JSON.stringify({runId:state.runId,promptId:state.promptId,currentProcessor:last?.processor||'Queued',result},null,2))}</pre></section><section class="work-card"><strong>Ordered runtime events</strong><pre>${escapeText(JSON.stringify(state.run.events,null,2))}</pre></section>${proof?`<section class="work-card"><strong>Hash proof</strong><pre>${escapeText(JSON.stringify(proof,null,2))}</pre></section>`:''}`}
function escapeText(s){return String(s).replace(/[&<>]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;'}[c]))}
function closeEvents(){if(state.source){state.source.close();state.source=null}if(state.eventAbort){state.eventAbort.abort();state.eventAbort=null}}
function connectNativeEvents(){closeEvents();setConnection('connecting','event stream');const src=new EventSource(`/api/runs/${encodeURIComponent(state.runId)}/events`,{withCredentials:true});state.source=src;src.onopen=()=>setConnection('connected');src.onmessage=e=>{try{void applyEvent(JSON.parse(e.data))}catch(err){toast(`Event parse error: ${err.message||err}`)}};src.onerror=()=>{if(state.run?.events?.some(isTerminalEvent)){closeEvents();return}setConnection('reconnecting','event stream')}}
async function connectBearerEvents(){closeEvents();const controller=new AbortController();state.eventAbort=controller;let delay=900;while(!controller.signal.aborted&&!state.run?.events?.some(isTerminalEvent)){try{setConnection('connecting','event stream');const r=await apiFetch(`/api/runs/${encodeURIComponent(state.runId)}/events`,{headers:{Accept:'text/event-stream'},signal:controller.signal});if(!r.ok)throw new Error(`Event stream failed: ${r.status}`);if(!r.body)throw new Error('Event stream body unavailable');setConnection('connected');delay=900;const reader=r.body.getReader(),decoder=new TextDecoder();let buffer='';while(!controller.signal.aborted){const {value,done}=await reader.read();if(done)break;buffer+=decoder.decode(value,{stream:true});buffer=buffer.replace(/\r\n/g,'\n');let i;while((i=buffer.indexOf('\n\n'))>=0){const block=buffer.slice(0,i);buffer=buffer.slice(i+2);const data=block.split('\n').filter(x=>x.startsWith('data:')).map(x=>x.slice(5).trimStart()).join('\n');if(data)await applyEvent(JSON.parse(data))}}}catch(e){if(controller.signal.aborted||state.run?.events?.some(isTerminalEvent))break;if(String(e).includes('Authentication'))break;setConnection('reconnecting','event stream');await new Promise(r=>setTimeout(r,delay));delay=Math.min(5000,Math.round(delay*1.7))}}}
function connectEvents(){state.authToken?void connectBearerEvents():connectNativeEvents()}

async function submitMessage(){const input=$('#message'),text=input.value.trim();if(!text)return;addMessage('user',text);input.value='';setReadiness(1,false,'Evaluating');try{let r;if(!state.conversationId)r=await apiFetch('/api/conversations',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({message:text})});else r=await apiFetch(`/api/conversations/${encodeURIComponent(state.conversationId)}/messages`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({message:text})});if(!r.ok)throw new Error(`Conversation request failed: ${r.status}`);const c=await r.json();if(c.conversation_id){state.conversationId=String(c.conversation_id);localStorage.setItem('oneshot.currentConversationId',state.conversationId)}const n=normalizeConversation(c);const explicitReady=n.intent?.ready_for_prompt;const ready=explicitReady!==undefined?!!explicitReady:c.sufficient===true;if(ready){state.promptId=String(c.prompt_id||n.intent?.prompt_id||state.promptId||'');if(state.promptId)localStorage.setItem('oneshot.currentPromptId',state.promptId);setReadiness(3,true,'Ready');if(c.message?.content)addMessage('assistant',c.message.content)}else{let help=n.help;if(!help&&state.conversationId){const pr=await apiFetch(`/api/conversations/${encodeURIComponent(state.conversationId)}/prompt`,{method:'POST'});const pd=await pr.json().catch(()=>({}));if(pr.status!==409&&!pr.ok)throw new Error(`Prompt readiness failed: ${pr.status}`);help=pd.help_request||pd.current_intent?.help_request||pd.intent?.help_request;if(pd.prompt_id){state.promptId=String(pd.prompt_id);localStorage.setItem('oneshot.currentPromptId',state.promptId)}}const question=help?.question||help?.reason||n.intent?.missing_required_information?.join(', ')||c.message?.content||'Additional information required.';addMessage('assistant',question);setReadiness(1,false,'More information')}}catch(e){if(!String(e).includes('Authentication'))addMessage('system',`OneShot runtime error: ${e.message||e}`);setReadiness(0,false,'Runtime unavailable')}}
$('#send').onclick=submitMessage;$('#message').onkeydown=e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();void submitMessage()}};
$('#generate').onclick=async()=>{if(!state.ready||!state.conversationId)return;$('#generate').disabled=true;try{const r=await apiFetch(`/api/conversations/${encodeURIComponent(state.conversationId)}/run`,{method:'POST',headers:{'Content-Type':'application/json'}});if(!r.ok)throw new Error(`Run initiation failed: ${r.status}`);const d=await r.json();if(!d.run_id)throw new Error('Run initiation response did not include run_id');state.runId=String(d.run_id);state.promptId=String(d.prompt_id||state.promptId||'');localStorage.setItem('oneshot.currentRunId',state.runId);if(state.promptId)localStorage.setItem('oneshot.currentPromptId',state.promptId);state.run={events:[],snapshot:null};state.seen.clear();$('#researcher-activity').innerHTML='';$$('.stage').forEach(x=>{x.dataset.state='PENDING';x.querySelector('em').textContent='PENDING'});$('#researcher summary').dataset.state='PENDING';$('#researcher summary em').textContent='PENDING';$('#run-meta').textContent=[state.promptId&&`Prompt(${state.promptId})`,`Run ${state.runId}`].filter(Boolean).join(' · ');openDrawer('tasks');view.onRunCreated();live.reset();tasks.resetPlan();await refreshRun().catch(()=>{});connectEvents();renderWork()}catch(e){toast(e.message||String(e));setReadiness(3,true,'Ready')}};

const op=$('#operator'),handle=$('#operator-handle'),work=$('#workspace');
function workBox(){return{w:work.clientWidth,h:work.clientHeight}}function opRect(){return{x:parseFloat(op.style.left)||op.offsetLeft,y:parseFloat(op.style.top)||op.offsetTop,w:op.offsetWidth,h:op.offsetHeight}}
function placeOp(x,y,w,h){const b=workBox(),minW=Math.min(260,Math.max(200,b.w-16)),minH=Math.min(80,Math.max(60,b.h-16));w=Math.max(minW,Math.min(w,b.w-16));h=Math.max(minH,Math.min(h,b.h-16));x=Math.max(8,Math.min(x,b.w-w-8));y=Math.max(8,Math.min(y,b.h-h-8));Object.assign(op.style,{left:`${x}px`,top:`${y}px`,bottom:'auto',transform:'none',width:`${w}px`,height:`${h}px`})}
function saveOp(){const b=workBox(),r=opRect();if(!b.w||!b.h)return;localStorage.setItem('oneshot.operator.v3',JSON.stringify({x:r.x/b.w,y:r.y/b.h,w:r.w/b.w,h:r.h/b.h}))}function restoreOp(){try{const s=JSON.parse(localStorage.getItem('oneshot.operator.v3')||'null');const b=workBox();if(s){placeOp(s.x*b.w,s.y*b.h,s.w*b.w,s.h*b.h);return}}catch{}const b=workBox(),w=Math.min(760,Math.max(340,b.w-32)),h=Math.min(164,Math.max(132,b.h-32));placeOp((b.w-w)/2,b.h-h-20,w,h)}
let drag;handle.onpointerdown=e=>{if(e.button!==0)return;const r=opRect(),wr=work.getBoundingClientRect();drag={id:e.pointerId,dx:e.clientX-wr.left-r.x,dy:e.clientY-wr.top-r.y,w:r.w,h:r.h};handle.setPointerCapture?.(e.pointerId)};handle.onpointermove=e=>{if(!drag||drag.id!==e.pointerId)return;const wr=work.getBoundingClientRect();placeOp(e.clientX-wr.left-drag.dx,e.clientY-wr.top-drag.dy,drag.w,drag.h)};function endDrag(e){if(!drag||drag.id!==e.pointerId)return;drag=null;saveOp()}handle.onpointerup=endDrag;handle.onpointercancel=endDrag;
let resize;$$('#operator [data-resize]').forEach(h=>{h.onpointerdown=e=>{if(e.button!==0)return;const r=opRect();resize={id:e.pointerId,dir:h.dataset.resize,ox:r.x,oy:r.y,w:r.w,h:r.h,x:e.clientX,y:e.clientY};h.setPointerCapture?.(e.pointerId);e.stopPropagation()};h.onpointermove=e=>{if(!resize||resize.id!==e.pointerId)return;let x=resize.ox,y=resize.oy,w=resize.w,hh=resize.h;const dx=e.clientX-resize.x,dy=e.clientY-resize.y,d=resize.dir;if(d.includes('e'))w=resize.w+dx;if(d.includes('s'))hh=resize.h+dy;if(d.includes('w')){w=resize.w-dx;x=resize.ox+dx}if(d.includes('n')){hh=resize.h-dy;y=resize.oy+dy}placeOp(x,y,w,hh)};h.onpointerup=e=>{if(resize?.id===e.pointerId){resize=null;saveOp()}};h.onpointercancel=h.onpointerup});
let railDrag,railJustDragged=false;const railStack=$('#rail-stack'),rail=$('#rail');function railTop(t){return Math.max(10,Math.min(t,Math.max(10,rail.clientHeight-railStack.offsetHeight-34)))}function saveRail(){const max=Math.max(1,rail.clientHeight-railStack.offsetHeight-44),top=parseFloat(railStack.style.top)||10;localStorage.setItem('oneshot.rail.y',String((top-10)/max))}function restoreRail(){const raw=localStorage.getItem('oneshot.rail.y');if(raw===null){railStack.style.top='10px';return}const ratio=Math.max(0,Math.min(1,Number(raw)||0)),max=Math.max(0,rail.clientHeight-railStack.offsetHeight-44);railStack.style.top=`${10+ratio*max}px`}railStack.onpointerdown=e=>{if(e.button!==0)return;railDrag={id:e.pointerId,startY:e.clientY,startTop:parseFloat(getComputedStyle(railStack).top)||10,moved:false};railJustDragged=false};document.addEventListener('pointermove',e=>{if(!railDrag||railDrag.id!==e.pointerId)return;const dy=e.clientY-railDrag.startY;if(!railDrag.moved&&Math.abs(dy)<7)return;railDrag.moved=true;railJustDragged=true;railStack.classList.add('dragging');railStack.style.top=`${railTop(railDrag.startTop+dy)}px`;e.preventDefault()});document.addEventListener('pointerup',e=>{if(!railDrag||railDrag.id!==e.pointerId)return;const moved=railDrag.moved;railDrag=null;railStack.classList.remove('dragging');if(moved){saveRail();setTimeout(()=>railJustDragged=false,0)}});const taskClick=$('#tasks-button').onclick,contextClick=$('#context-button').onclick;$('#tasks-button').onclick=e=>{if(railJustDragged){e.preventDefault();return}taskClick(e)};$('#context-button').onclick=e=>{if(railJustDragged){e.preventDefault();return}contextClick(e)};
function syncLayout(){requestAnimationFrame(()=>requestAnimationFrame(()=>setTimeout(()=>{if(drag||resize)return;restoreOp();restoreRail()},220)))}window.addEventListener('resize',syncLayout);

async function restoreRun(){if(!state.runId)return;try{state.run={events:[],snapshot:null};state.seen.clear();await refreshRun();$('#run-meta').textContent=[state.promptId&&`Prompt(${state.promptId})`,`Run ${state.runId}`].filter(Boolean).join(' · ');connectEvents()}catch(e){if(String(e).includes('404')){localStorage.removeItem('oneshot.currentRunId');state.runId=''}else if(!String(e).includes('Authentication'))toast(`Run restore unavailable: ${e.message||e}`)}}
async function bootstrap(){syncSide();restoreOp();restoreRail();setConnection('connecting');try{const r=await apiFetch('/api/health');if(!r.ok)throw new Error(`Health check failed: ${r.status}`);const h=await r.json();setConnection('connected',[h.mode,h.provider].filter(Boolean).join(' · '))}catch(e){if(!String(e).includes('Authentication'))setConnection('disconnected',e.message||String(e))}await loadWorkspace();await restoreRun();setReadiness(0,false,state.runId?'Run restored':'Awaiting request')}
window.addEventListener('beforeunload',closeEvents);void bootstrap();
