import test from "node:test";
import assert from "node:assert/strict";
import { clone } from "../../core/clone.js";
import type { Fixture, ResearchBundle } from "../../contract/types.js";
import type { ResearchProvider } from "../../role/researcher/provider.js";
import { harness, prompt } from "./harness.js";
import { WorkflowRootCauseError } from "../../core/root-cause-error.js";

const seven=(b:ResearchBundle):Fixture=>({fixture_id:b.fixture.fixture_id,researcher_id:b.fixture.researcher_id,plan_assertions:[
 {assertion_id:"op:exists",operator:"exists",target:"$.plan_id",evidence_ids:b.researcher.success_definition.evidence_ids},
 {assertion_id:"op:equals",operator:"equals",target:"$.plan_id",expected:b.plan.plan_id,evidence_ids:b.researcher.success_definition.evidence_ids},
 {assertion_id:"op:contains",operator:"contains",target:"$.steps.0.requirement_refs",expected:b.plan.requirements[0].requirement_id,evidence_ids:b.researcher.success_definition.evidence_ids},
 {assertion_id:"op:matches",operator:"matchesSchema",target:"$",expected:"urn:oneshot:schema:plan:1",evidence_ids:b.researcher.success_definition.evidence_ids},
 {assertion_id:"op:references",operator:"references",target:"$.steps.0.goal_refs",expected:b.goal.success_criteria[0].criterion_id,evidence_ids:b.researcher.success_definition.evidence_ids},
 {assertion_id:"op:edge",operator:"edgeExists",target:"$.plan_id",expected:{from:"Researcher",to:"Planner",artifact:"plan_id"},evidence_ids:b.researcher.success_definition.evidence_ids},
 {assertion_id:"op:files",operator:"allFilesSpecified",target:"$.steps.0.requirement_refs",expected:[b.plan.requirements[0].requirement_id],evidence_ids:b.researcher.success_definition.evidence_ids}
]});

test("canonical Role/runtime fixture matrix",async(t)=>{const h=await harness("matrix");try{const runId="matrix",b=await h.researcher.run(prompt(runId),runId);
 await t.test("plan identity through Planner and Refactor",async()=>{const x=clone(b);x.plan.steps[0].goal_refs=[];const audit=await h.planner.run(x,"matrix-refactor");assert.ok(audit.findings.length);const before=x.plan.plan_id,rev=x.plan.revision;const out=await h.refactor.run(x,audit);assert.equal(out.plan_id,before);assert.equal(out.revision,rev+1);assert.ok(out.revision_evidence.length);});
 await t.test("Gap correction performs fresh recheck",async()=>{const x=clone(b);x.plan.steps[0].requirement_refs=[];const out=await h.gapper.run(x,x.plan);assert.equal(out.gap.result,"PASSED");assert.equal(out.gap.gap_0,true);assert.ok(out.gap.resolved_gaps.length);});
 await t.test("Evaluation ROOT_CAUSE has all nine evidence areas",async()=>{const x=clone(b);x.plan.steps[0].goal_refs=[];const e=await h.evaluator.run(x,x.plan);assert.equal(e.result,"ROOT_CAUSE");assert.equal(e.evidence.length,9);});
 await t.test("Triple VALID",async()=>{const r=await h.triple.run(b,b.plan);assert.equal(r.all_valid,true);});
 await t.test("Schema NOT_VALID and invalid schema document",async()=>{const x=clone(b);x.schema_artifact.schema_document={type:"object",properties:{plan_id:{const:"wrong"}}} as any;let r=await h.triple.run(x,x.plan);assert.equal(r.schema_validation.result,"NOT_VALID");x.schema_artifact.schema_document={type:123} as any;r=await h.triple.run(x,x.plan);assert.equal(r.schema_validation.result,"NOT_VALID");});
 await t.test("Fixture NOT_VALID",async()=>{const x=clone(b);x.fixture.plan_assertions[0].expected="wrong";const r=await h.triple.run(x,x.plan);assert.equal(r.fixture_validation.result,"NOT_VALID");});
 await t.test("Goal NOT_VALID",async()=>{const x=clone(b);x.plan.steps[0].goal_refs=[];const r=await h.triple.run(x,x.plan);assert.equal(r.goal_validation.result,"NOT_VALID");});
 await t.test("validation_id routes exact assertions and criteria",async()=>{const x=clone(b);x.fixture.plan_assertions.push({assertion_id:"not-routed",operator:"equals",target:"$.plan_id",expected:"wrong",evidence_ids:x.researcher.success_definition.evidence_ids});x.goal.success_criteria.push({...x.goal.success_criteria[0],criterion_id:"not-routed-criterion"});const r=await h.triple.run(x,x.plan);assert.equal(r.fixture_validation.result,"VALID");assert.equal(r.fixture_validation.assertion_results.length,1);assert.equal(r.goal_validation.criterion_results.length,1);});
 await t.test("validation routing identity mismatch rejects before proof",async()=>{const x=clone(b);x.validation.fixture_validation.plan_id="other";await assert.rejects(()=>h.triple.run(x,x.plan),/validation routing mismatch/);});
 await t.test("all fixture operators positive and negative through Triple Validation",async()=>{const x=clone(b);x.fixture=seven(x);x.validation.fixture_validation.assertion_ids=x.fixture.plan_assertions.map(a=>a.assertion_id);let r=await h.triple.run(x,x.plan);assert.equal(r.fixture_validation.result,"VALID");const changes:Record<string,(a:any)=>void>={"op:exists":a=>a.target="$.missing","op:equals":a=>a.expected="wrong","op:contains":a=>a.expected="missing","op:matches":a=>a.expected="urn:oneshot:schema:prompt:1","op:references":a=>a.expected="missing","op:edge":a=>a.expected={from:"Nowhere",to:"Planner"},"op:files":a=>a.expected=["missing"]};for(const [id,mutate] of Object.entries(changes)){const y=clone(x);mutate(y.fixture.plan_assertions.find(a=>a.assertion_id===id));r=await h.triple.run(y,y.plan);assert.equal(r.fixture_validation.result,"NOT_VALID",id);}});
 await t.test("unknown and missing fields reject through canonical Skill",async()=>{await assert.rejects(()=>h.contracts.validate("urn:oneshot:schema:audit:1",{audit_id:"a",researcher_id:"r",plan_id:"p",reviewed_areas:[],findings:[],severity:"HIGH"}),/severity/);const bad:any=clone(b.researcher);delete bad.plan_id;await assert.rejects(()=>h.contracts.validate("urn:oneshot:schema:researcher:1",bad),/plan_id/);});
 await t.test("canonical ordering, hash equality and content mutation",async()=>{const a=await h.contracts.invoke<any>("canonicalize",{value:{b:1,a:2}}),c=await h.contracts.invoke<any>("canonicalize",{value:{a:2,b:1}});assert.equal(a.canonical_utf8,c.canonical_utf8);const audit=await h.planner.run(b,"matrix-confirm"),p=await h.refactor.run(b,audit),g=await h.gapper.run(b,p),e=await h.evaluator.run(b,g.plan),tr=await h.triple.run(b,g.plan),pkg=await h.confirmation.run(b,g.plan,audit,g.gap,e,tr),created=await h.contracts.createHash(pkg.core),proof=await h.contracts.verifyHash(pkg.core,created);assert.equal(proof.equal,true);const mutated=clone(pkg.core);mutated.plan.steps[0].description="changed";assert.equal((await h.contracts.verifyHash(mutated,created)).equal,false);});
 await t.test("workflow graph and Skill registry",async()=>{await h.contracts.verifyStatic();assert.deepEqual(h.contracts.definitions().map(x=>x.name).sort(),["canonicalize","create_hash","resolve_artifact","run_fixture","trace_artifact","validate_artifact","validate_graph","validate_parity","validate_references","validate_registry","validate_schema","verify_hash"]);});
 }finally{h.bridge.close();}});

test("provider/runtime failure terminates visibly at Done ROOT_CAUSE",async()=>{const provider:ResearchProvider={async research(_p,_r){throw new WorkflowRootCauseError({issue:"provider",expected:"configured provider",actual:"provider failed",evidence_ids:[],required_correction:"configure provider",recheck_target:"provider"});}};const h=await harness("provider-failure",provider);const runId="provider-failure";h.runs.create(runId);try{const out=await h.runtime.run(runId,prompt(runId));assert.equal(out.result,"ROOT_CAUSE");const done=out.events.filter(e=>e.processor==="Done"&&e.state==="COMPLETE").at(-1);assert.equal(done?.result,"ROOT_CAUSE");assert.equal(out.root_cause?.actual,"provider failed");}finally{h.bridge.close();}});
